# configure vpn tunnel
## configure vpn policy for the tunnel interface
send_with_pause "vpn policy tunnel-interface $vpn_policy_name $newline"
expect "#"
send_with_pause "enable $newline"
expect "#"

send_with_pause "gateway primary $vpn_gateway_dns_name_sonicwall_format $newline"
expect "#"
send_with_pause "auth-method shared-secret $newline"
expect "#"
send_with_pause "shared-secret $vpn_connection_shared_key $newline"
expect "#"
send_with_pause "exit $newline"
expect "#"
send_with_pause "proposal ike exchange ikev2 $newline"
expect "#"
send_with_pause "proposal ike dh-group 14 $newline"
expect "#"
send_with_pause "proposal ike encryption aes-256 $newline"
expect "#"
send_with_pause "proposal ike authentication sha-1 $newline"
expect "#"
send_with_pause "proposal ike lifetime 36000 $newline"
expect "#"
send_with_pause "proposal ipsec protocol esp $newline"
expect "#"
send_with_pause "proposal ipsec encryption aes-256 $newline"
expect "#"
send_with_pause "proposal ipsec authentication sha-1 $newline"
expect "#"
send_with_pause "proposal ipsec perfect-forward-secrecy dh-group 14 $newline"
expect "#"
send_with_pause "proposal ipsec lifetime 10800 $newline"
expect "#"
send_with_pause "keep-alive $newline"
expect "#"
send_with_pause "suppress-trigger-packet $newline"
expect "#"
send_with_pause "bound-to interface X1 $newline"
expect "#"
send_with_pause "exit $newline"
expect "#"
send_with_pause "commit $newline"
expect "$config_prompt"
