## configure tunnel interface
send_with_pause "tunnel-interface vpn $interface_name $newline"
expect "#"
send_with_pause "policy $vpn_policy_name $newline"
expect "#"
send_with_pause "ip-assignment VPN static $newline"
expect "#"
send_with_pause "ip $sonicwall_tunnel_interface_ip netmask $tunnel_interface_netmask $newline"
expect "#"
send_with_pause "exit $newline"
expect "#"
send_with_pause "flow-reporting $newline"
expect "#"
send_with_pause "fragment-packets $newline"
expect "#"
send_with_pause "exit $newline"
expect "$config_prompt"
## commit changes
send_with_pause "commit $newline"
expect "$config_prompt"
